package com.cavale.user.repository;

import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.annotation.Import;

import com.cavale.TestcontainersConfiguration;
import com.cavale.user.domain.User;
import com.cavale.common.config.JpaAuditingConfig;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@Import({TestcontainersConfiguration.class, JpaAuditingConfig.class})
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    void save_populatesDbGeneratedIdAndAuditTimestamps() {
        User alice = new User("alice@cavale.run", "hash", "Alice");

        User saved = userRepository.saveAndFlush(alice);

        assertThat(saved.getId()).as("id generated by uuidv7()").isNotNull();
        assertThat(saved.getCreatedAt()).as("createdAt set by auditing").isNotNull();
        assertThat(saved.getUpdatedAt()).as("updatedAt set by auditing").isNotNull();
    }

    @Test
    void findByEmail_returnsSavedUser() {
        userRepository.saveAndFlush(new User("alice@cavale.run", "hash", "Alice"));

        Optional<User> found = userRepository.findByEmail("alice@cavale.run");

        assertThat(found).isPresent();
        assertThat(found.get().getDisplayName()).isEqualTo("Alice");
    }

    @Test
    void findByEmail_returnsEmptyForUnknownEmail() {
        Optional<User> found = userRepository.findByEmail("nobody@cavale.run");

        assertThat(found).isEmpty();
    }

    @Test
    void existsByEmail_reflectsPresence() {
        userRepository.saveAndFlush(new User("bob@cavale.run", "hash", "Bob"));

        assertThat(userRepository.existsByEmail("bob@cavale.run")).isTrue();
        assertThat(userRepository.existsByEmail("nobody@cavale.run")).isFalse();
    }
}
